objects=  sh_test.o ../../voevodin/sh_ccydalib/sh_ccydalib.o -lrt
sh_test:  $(objects)
	$(CC) -o sh_test  $(objects) ../../voevodin/ccydalib/ccydalib.a
sh_test.o: ../../voevodin/sh_ccydalib/sh_ccydalib.h 

